# ==============================================================================
# Merged Lakeflow Source: dicomweb
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import (
    date,
    datetime,
    timedelta,
    timezone,
)
from decimal import Decimal
from typing import Any, Iterator
import json
import os
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from urllib.error import HTTPError
from pyspark.sql.types import *
import base64
import logging
import urllib.error
import urllib.parse
import urllib.request


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/sources/dicomweb/dicomweb_client.py
    ########################################################

    logger = logging.getLogger(__name__)

    # Default socket timeout (seconds) — used for connect + read
    _DEFAULT_TIMEOUT = 60


    class DICOMwebClient:
        """Thin HTTP wrapper around a DICOMweb endpoint (QIDO-RS + WADO-RS)."""

        def __init__(
            self,
            base_url: str,
            auth: dict[str, str] | None = None,
            timeout: int = _DEFAULT_TIMEOUT,
        ) -> None:
            self.base_url = base_url.rstrip("/")
            # Accept both a plain int and the legacy (connect, read) tuple
            self.timeout = max(timeout) if isinstance(timeout, tuple) else timeout
            self._default_headers: dict[str, str] = {"Accept": "application/dicom+json"}

            auth = auth or {}
            username = auth.get("username")
            password = auth.get("password")
            token = auth.get("token")

            if username and password:
                credentials = base64.b64encode(f"{username}:{password}".encode()).decode()
                self._default_headers["Authorization"] = f"Basic {credentials}"
            elif token:
                self._default_headers["Authorization"] = f"Bearer {token}"

        # ------------------------------------------------------------------
        # Internal HTTP helper
        # ------------------------------------------------------------------

        def _get(
            self,
            url: str,
            extra_headers: dict[str, str] | None = None,
            params: dict[str, Any] | None = None,
        ):
            """Execute a GET request and return an http.client.HTTPResponse."""
            if params:
                url = f"{url}?{urllib.parse.urlencode(params)}"
            headers = {**self._default_headers, **(extra_headers or {})}
            req = urllib.request.Request(url, headers=headers)
            return urllib.request.urlopen(req, timeout=self.timeout)

        # ------------------------------------------------------------------
        # QIDO-RS helpers
        # ------------------------------------------------------------------

        def _qido_get(self, path: str, params: dict[str, Any]) -> list[dict]:
            """Execute a QIDO-RS GET and return the parsed JSON list."""
            url = f"{self.base_url}{path}"
            logger.debug("QIDO-RS GET %s params=%s", url, params)
            resp = self._get(url, params=params)
            if resp.status == 204:
                # No content — valid empty response
                return []
            body = resp.read()
            # Some servers return empty body instead of 204
            if not body:
                return []
            return json.loads(body)

        def query_studies(
            self,
            study_date_range: str,
            limit: int = 100,
            offset: int = 0,
        ) -> list[dict]:
            """
            QIDO-RS: GET /studies?StudyDate={range}&limit={n}&offset={n}

            Args:
                study_date_range: DICOMweb date range string, e.g. "20231201-20231215".
                limit:            Max records per page.
                offset:           Zero-based record offset for pagination.

            Returns:
                List of DICOM JSON objects (dicts keyed by 8-char hex tag strings).
            """
            params: dict[str, Any] = {
                "StudyDate": study_date_range,
                "limit": limit,
                "offset": offset,
            }
            return self._qido_get("/studies", params)

        def query_series_for_study(self, study_uid: str) -> list[dict]:
            """
            QIDO-RS: GET /studies/{study_uid}/series

            Hierarchical endpoint returning all series belonging to a single study.
            Required by S3 Static WADO Server and recommended by the DICOMweb standard.

            Args:
                study_uid: DICOM study UID.

            Returns:
                List of DICOM JSON objects (dicts keyed by 8-char hex tag strings).
            """
            return self._qido_get(f"/studies/{study_uid}/series", {})

        def query_instances_for_series(self, study_uid: str, series_uid: str) -> list[dict]:
            """
            QIDO-RS: GET /studies/{study_uid}/series/{series_uid}/instances

            Hierarchical endpoint returning all instances belonging to a single series.

            Args:
                study_uid:  DICOM study UID.
                series_uid: DICOM series UID.

            Returns:
                List of DICOM JSON objects (dicts keyed by 8-char hex tag strings).
            """
            return self._qido_get(f"/studies/{study_uid}/series/{series_uid}/instances", {})

        # ------------------------------------------------------------------
        # WADO-RS
        # ------------------------------------------------------------------

        def retrieve_instance(
            self,
            study_uid: str,
            series_uid: str,
            sop_uid: str,
        ) -> bytes:
            """
            WADO-RS: retrieve a raw DICOM file.

            GET {base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}
            Accept: multipart/related; type="application/dicom"

            Returns:
                Raw bytes of the .dcm file (multipart/related — first part extracted).
            """
            url = f"{self.base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}"
            logger.debug("WADO-RS GET %s", url)
            resp = self._get(
                url, extra_headers={"Accept": 'multipart/related; type="application/dicom"'}
            )
            content_type = resp.headers.get("Content-Type", "")
            body = resp.read()
            if "multipart/related" in content_type:
                return _extract_first_multipart_part(body, content_type)
            # Some servers return raw DICOM directly
            return body

        def retrieve_instance_frames(
            self,
            study_uid: str,
            series_uid: str,
            sop_uid: str,
            frame_number: int = 1,
        ) -> bytes:
            """
            WADO-RS: retrieve a specific frame from a DICOM instance.

            Used by S3 Static WADO Server and other frame-based servers that do not
            support full DICOM file retrieval via the standard WADO-RS instance endpoint.

            GET {base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/frames/{n}

            Args:
                study_uid:    DICOM study UID.
                series_uid:   DICOM series UID.
                sop_uid:      DICOM SOP instance UID.
                frame_number: 1-based frame index (default: 1).

            Returns:
                Raw bytes of the frame image (JPEG, PNG, or similar).
            """
            url = (
                f"{self.base_url}/studies/{study_uid}/series/{series_uid}"
                f"/instances/{sop_uid}/frames/{frame_number}"
            )
            logger.debug("WADO-RS frames GET %s", url)
            resp = self._get(
                url, extra_headers={"Accept": "image/jpeg, image/png, application/octet-stream"}
            )
            content_type = resp.headers.get("Content-Type", "")
            body = resp.read()
            if "multipart/related" in content_type:
                return _extract_first_multipart_part(body, content_type)
            return body

        def retrieve_instance_metadata(
            self,
            study_uid: str,
            series_uid: str,
            sop_uid: str,
        ) -> dict:
            """
            WADO-RS: retrieve full DICOM JSON metadata for a single instance.

            GET {base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/metadata
            Accept: application/dicom+json

            Returns the complete DICOM JSON object for this SOP instance (all tags).
            More targeted than retrieve_series_metadata() when only one instance
            is needed — avoids downloading metadata for all siblings in the series.

            Args:
                study_uid:  DICOM study UID.
                series_uid: DICOM series UID.
                sop_uid:    DICOM SOP instance UID.

            Returns:
                Single full DICOM JSON object (dict keyed by 8-char hex tag strings).
                Returns an empty dict if the server returns 204 or an empty body.
            """
            url = (
                f"{self.base_url}/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/metadata"
            )
            logger.debug("WADO-RS instance metadata GET %s", url)
            resp = self._get(url, extra_headers={"Accept": "application/dicom+json"})
            if resp.status == 204:
                return {}
            body = resp.read()
            if not body:
                return {}
            data = json.loads(body)
            # Some servers return a list with one element, others return the object directly
            if isinstance(data, list):
                return data[0] if data else {}
            return data

        def retrieve_series_metadata(
            self,
            study_uid: str,
            series_uid: str,
        ) -> list[dict]:
            """
            WADO-RS: retrieve full DICOM JSON metadata for all instances in a series.

            GET {base_url}/studies/{study_uid}/series/{series_uid}/metadata
            Accept: application/dicom+json

            Returns a list of complete DICOM JSON objects — one per instance — with
            all tags (not just the subset returned by QIDO-RS).  Useful for populating
            the `metadata` variant column or for servers (e.g. S3 Static WADO) that
            serve instance data via this endpoint rather than via QIDO-RS /instances.

            Args:
                study_uid:  DICOM study UID.
                series_uid: DICOM series UID.

            Returns:
                List of full DICOM JSON objects (one per SOP instance).
            """
            url = f"{self.base_url}/studies/{study_uid}/series/{series_uid}/metadata"
            logger.debug("WADO-RS metadata GET %s", url)
            resp = self._get(url, extra_headers={"Accept": "application/dicom+json"})
            if resp.status == 204:
                return []
            body = resp.read()
            if not body:
                return []
            return json.loads(body)

        def probe_endpoint(self, path: str, accept: str | None = None) -> dict:
            """
            Make a lightweight probe request and return capability information.

            Used by the `diagnostics` table to test which DICOMweb endpoints are
            available on the target server without raising exceptions.

            Args:
                path:   URL path relative to base_url (already includes query string
                        if needed, e.g. "/studies?limit=1").
                accept: Optional Accept header override.

            Returns:
                dict with keys: status_code (int|None), content_type (str|None),
                latency_ms (int), error (str|None).
            """
            url = f"{self.base_url}{path}"
            extra_headers = {"Accept": accept} if accept else None
            t0 = time.monotonic()
            try:
                resp = self._get(url, extra_headers=extra_headers)
                latency_ms = int((time.monotonic() - t0) * 1000)
                return {
                    "status_code": resp.status,
                    "content_type": resp.headers.get("Content-Type", ""),
                    "latency_ms": latency_ms,
                    "error": None,
                }
            except urllib.error.HTTPError as exc:
                # HTTP error responses (4xx/5xx) are valid probe results, not failures
                latency_ms = int((time.monotonic() - t0) * 1000)
                return {
                    "status_code": exc.code,
                    "content_type": exc.headers.get("Content-Type", ""),
                    "latency_ms": latency_ms,
                    "error": None,
                }
            except Exception as exc:
                latency_ms = int((time.monotonic() - t0) * 1000)
                return {
                    "status_code": None,
                    "content_type": None,
                    "latency_ms": latency_ms,
                    "error": str(exc),
                }


    # ---------------------------------------------------------------------------
    # Multipart helpers
    # ---------------------------------------------------------------------------


    def _extract_first_multipart_part(body: bytes, content_type: str) -> bytes:
        """
        Extract the raw bytes of the first part from a MIME multipart body.

        The boundary is parsed from the Content-Type header, e.g.:
            multipart/related; type="application/dicom"; boundary="myboundary"
        """
        boundary = _parse_boundary(content_type)
        if not boundary:
            # Can't parse boundary — return whole body and hope for the best
            return body

        sep = f"--{boundary}".encode()
        parts = body.split(sep)
        # parts[0] is preamble (empty), parts[1] is first part, parts[-1] is "--\r\n"
        for part in parts[1:]:
            if part.strip() in (b"", b"--", b"--\r\n", b"--\n"):
                continue
            # Strip part headers (blank line separates headers from body)
            if b"\r\n\r\n" in part:
                return part.split(b"\r\n\r\n", 1)[1].rstrip(b"\r\n")
            if b"\n\n" in part:
                return part.split(b"\n\n", 1)[1].rstrip(b"\n")
            return part
        return body


    def _parse_boundary(content_type: str) -> str | None:
        """Extract the multipart boundary from a Content-Type header value."""
        for segment in content_type.split(";"):
            segment = segment.strip()
            if segment.lower().startswith("boundary="):
                boundary = segment[len("boundary=") :].strip().strip('"')
                return boundary
        return None


    ########################################################
    # src/databricks/labs/community_connector/sources/dicomweb/dicomweb_datasource.py
    ########################################################

    @dataclass
    class SimplePartition(InputPartition):
        """Single partition carrying the serialised start-offset."""

        start_json: str


    @dataclass
    class DicomBatchPartition(InputPartition):
        """Batch of instance records to process on an executor."""

        instances_json: str
        options_json: str


    # ---------------------------------------------------------------------------
    # DataSourceStreamReader — runs read() on executors
    # ---------------------------------------------------------------------------


    class DicomStreamReader(DataSourceStreamReader):
        """Executor-distributed streaming reader for DICOMweb.

        * Non-file tables and instances without ``fetch_dicom_files`` /
          ``fetch_metadata``: a single ``SimplePartition`` is returned and
          ``read()`` queries the source normally on one executor.

        * Instances with file/metadata fetch enabled: ``partitions()`` collects
          bare instance records on the driver, then batches them into
          ``DicomBatchPartition`` objects.  Each ``read(DicomBatchPartition)``
          runs on a Spark executor with UC Volume FUSE access and performs the
          WADO-RS downloads there.
        """

        def __init__(self, options, schema, lakeflow_connect):
            self.options = options
            self.schema = schema
            self._lakeflow_connect = lakeflow_connect

        # -- offsets -------------------------------------------------------------

        def initialOffset(self):
            return {}

        def latestOffset(self):
            return {"study_date": date.today().strftime("%Y%m%d"), "page_offset": 0}

        # -- partitioning --------------------------------------------------------

        def partitions(self, start, end):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            table_options = {k: v for k, v in self.options.items() if k != IS_DELETE_FLOW}
            table_name = self.options.get(TABLE_NAME)
            fetch_files = table_options.get("fetch_dicom_files", "false").lower() == "true"
            fetch_metadata = table_options.get("fetch_metadata", "false").lower() == "true"
            volume_path = table_options.get("dicom_volume_path", "")

            if not is_delete_flow and table_name == "instances" and (fetch_files or fetch_metadata):
                if fetch_files and not volume_path:
                    raise ValueError("fetch_dicom_files=true requires dicom_volume_path")
                return self._collect_instance_partitions(table_name, table_options, start)
            return [SimplePartition(start_json=json.dumps(start if start else {}))]

        def _collect_instance_partitions(self, table_name, table_options, start):
            """Driver-side: page through bare instance records, batch into partitions."""
            meta_options = dict(table_options)
            meta_options["fetch_dicom_files"] = "false"
            meta_options["fetch_metadata"] = "false"

            all_records = []
            current_start = dict(start) if start else {}
            while True:
                records, next_offset = self._lakeflow_connect.read_table(
                    table_name,
                    current_start,
                    meta_options,
                )
                batch = list(records)
                all_records.extend(batch)
                if not batch or next_offset.get("page_offset", 0) == 0:
                    break
                if next_offset == current_start:
                    break
                current_start = next_offset

            batch_size = int(self.options.get("dicom_batch_size", "50"))
            options_json = json.dumps(dict(self.options))
            return [
                DicomBatchPartition(
                    instances_json=json.dumps(all_records[i : i + batch_size], default=str),
                    options_json=options_json,
                )
                for i in range(0, max(1, len(all_records)), batch_size)
            ]

        # -- read (executor-side) ------------------------------------------------

        def read(self, partition):
            if isinstance(partition, DicomBatchPartition):
                return self._read_dicom_batch(partition)
            return self._read_simple(partition)

        def _read_dicom_batch(self, partition):
            """Executor: download DICOM files and/or fetch metadata."""
            instances = json.loads(partition.instances_json)
            options = json.loads(partition.options_json)
            table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}
            volume_path = table_options.get("dicom_volume_path", "")
            wado_mode = table_options.get("wado_mode", "auto")
            fetch_metadata = table_options.get("fetch_metadata", "false").lower() == "true"
            fetch_files = table_options.get("fetch_dicom_files", "false").lower() == "true"
            connector = LakeflowConnectImpl(options)

            if fetch_metadata:
                sop_to_meta: dict = {}
                seen_series: set = set()
                for rec in instances:
                    key = (rec.get("study_instance_uid"), rec.get("series_instance_uid"))
                    if key not in seen_series and all(key):
                        seen_series.add(key)
                        sop_to_meta.update(connector._build_metadata_map(key[0], key[1]))
                for rec in instances:
                    sop_uid = rec.get("sop_instance_uid")
                    rec["metadata"] = sop_to_meta.get(sop_uid) if sop_uid else None

            results = []
            for rec in instances:
                if fetch_files:
                    rec = connector._attach_dicom_file(rec, volume_path, wado_mode)
                results.append(parse_value(rec, self.schema))
            return iter(results)

        def _read_simple(self, partition):
            """Executor: query source and return records (no file downloads)."""
            start = json.loads(partition.start_json)
            table_name = self.options.get(TABLE_NAME)
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            table_options = {k: v for k, v in self.options.items() if k != IS_DELETE_FLOW}
            connector = LakeflowConnectImpl(self.options)
            if is_delete_flow:
                records, _ = connector.read_table_deletes(table_name, start, table_options)
            else:
                records, _ = connector.read_table(table_name, start, table_options)
            return iter(map(lambda x: parse_value(x, self.schema), records))

        def commit(self, end):
            pass


    # ---------------------------------------------------------------------------
    # __init_subclass__ hook — inject streamReader into LakeflowSource
    # ---------------------------------------------------------------------------
    # When lakeflow_datasource.py (merged after this section) defines
    # ``class LakeflowSource(DataSource)``, Python calls
    # ``DataSource.__init_subclass__(LakeflowSource)``.  We use this hook to
    # attach ``streamReader`` directly onto ``LakeflowSource.__dict__``.
    #
    # Because the base class remains the original pyspark DataSource (importable
    # on executors) and ``_stream_reader`` is a plain closure, cloudpickle
    # serialises everything by value — no ``databricks.labs`` module reference
    # ends up in the pickle stream.
    # ---------------------------------------------------------------------------


    @classmethod
    def _dicom_init_subclass(cls, **kwargs):
        def _stream_reader(self, schema):
            return DicomStreamReader(self.options, schema, self.lakeflow_connect)

        cls.streamReader = _stream_reader


    DataSource.__init_subclass__ = _dicom_init_subclass


    ########################################################
    # src/databricks/labs/community_connector/sources/dicomweb/dicomweb_parser.py
    ########################################################

    STUDY_TAG_MAP: dict[str, str] = {
        "0020000D": "study_instance_uid",
        "00080020": "study_date",
        "00080030": "study_time",
        "00080050": "accession_number",
        "00100010": "patient_name",
        "00100020": "patient_id",
        "00081030": "study_description",
        "00080061": "modalities_in_study",
        "00201206": "number_of_study_related_series",
        "00201208": "number_of_study_related_instances",
    }

    SERIES_TAG_MAP: dict[str, str] = {
        "0020000E": "series_instance_uid",
        "0020000D": "study_instance_uid",
        "00080020": "study_date",
        "00200011": "series_number",
        "0008103E": "series_description",
        "00080060": "modality",
        "00180015": "body_part_examined",
        "00080021": "series_date",
    }

    INSTANCE_TAG_MAP: dict[str, str] = {
        "00080018": "sop_instance_uid",
        "0020000E": "series_instance_uid",
        "0020000D": "study_instance_uid",
        "00080016": "sop_class_uid",
        "00200013": "instance_number",
        "00080020": "study_date",
        "00080023": "content_date",
        "00080033": "content_time",
    }

    # VRs that carry a single string scalar (or list → join / first element)
    _STRING_VRS = {"DA", "TM", "CS", "LO", "UI", "SH", "LT", "ST", "UT", "AE", "AS", "DT", "UC", "UR"}
    # VRs that carry numeric values
    _NUMERIC_VRS = {
        "IS",
        "DS",
        "FL",
        "FD",
        "SL",
        "SS",
        "UL",
        "US",
        "AT",
        "OB",
        "OW",
        "OF",
        "OD",
        "OL",
        "OV",
    }
    # Multi-valued string VRs (arrays stay as lists)
    _MULTI_STRING_VRS = {"CS"}  # modalities_in_study uses CS and can be multi-valued


    # ---------------------------------------------------------------------------
    # Low-level value extraction
    # ---------------------------------------------------------------------------


    def _extract_pn_value(first: object) -> object:
        """Extract a Person Name value from the first element."""
        if isinstance(first, dict):
            return first.get("Alphabetic") or first.get("Ideographic") or first.get("Phonetic")
        return str(first)


    def _extract_string_value(values: list, field_name: str) -> object:
        """Extract a string-type value, handling multi-valued fields."""
        if field_name == "modalities_in_study":
            return [str(v) for v in values]
        return str(values[0])


    def _extract_numeric_value(first: object, vr: str) -> object:
        """Extract a numeric value with appropriate int/float conversion."""
        try:
            if vr in {"IS", "US", "UL", "SS", "SL"}:
                return int(first)
            return float(first)
        except (TypeError, ValueError):
            return None


    def _extract_value(tag_obj: dict, field_name: str) -> object:
        """Extract a Python value from a DICOM JSON tag object."""
        vr = tag_obj.get("vr", "")
        values = tag_obj.get("Value", [])

        if not values:
            return None
        if vr == "PN":
            return _extract_pn_value(values[0])
        if vr in _STRING_VRS:
            return _extract_string_value(values, field_name)
        if vr in _NUMERIC_VRS:
            return _extract_numeric_value(values[0], vr)
        # Fallback: return first value as-is or stringified
        first = values[0]
        return first if isinstance(first, (str, int, float, bool)) else str(first)


    # ---------------------------------------------------------------------------
    # Public parse functions
    # ---------------------------------------------------------------------------


    def parse_dicom_json(dicom_obj: dict, tag_map: dict[str, str]) -> dict:
        """
        Convert a single DICOM JSON object to a Python dict using the given tag map.

        Args:
            dicom_obj: Dict keyed by 8-character uppercase hex tags.
            tag_map:   Mapping of hex tag → field name.

        Returns:
            Dict of {field_name: value} for all recognised tags that have a value.
        """
        result: dict = {}
        for tag, field_name in tag_map.items():
            tag_upper = tag.upper()
            tag_obj = dicom_obj.get(tag_upper) or dicom_obj.get(tag.lower())
            if tag_obj is None:
                result[field_name] = None
                continue
            result[field_name] = _extract_value(tag_obj, field_name)
        return result


    def parse_study(dicom_obj: dict) -> dict:
        """Parse a QIDO-RS study-level DICOM JSON object."""
        return parse_dicom_json(dicom_obj, STUDY_TAG_MAP)


    def parse_series(dicom_obj: dict) -> dict:
        """Parse a QIDO-RS series-level DICOM JSON object."""
        return parse_dicom_json(dicom_obj, SERIES_TAG_MAP)


    def parse_instance(dicom_obj: dict) -> dict:
        """Parse a QIDO-RS instance-level DICOM JSON object."""
        record = parse_dicom_json(dicom_obj, INSTANCE_TAG_MAP)
        # dicom_file_path is filled in later by the connector when WADO-RS retrieval is enabled
        record.setdefault("dicom_file_path", None)
        # metadata is filled in later when fetch_metadata=true
        record.setdefault("metadata", None)
        return record


    ########################################################
    # src/databricks/labs/community_connector/sources/dicomweb/dicomweb_schemas.py
    ########################################################

    STUDIES_SCHEMA = StructType(
        [
            StructField("study_instance_uid", StringType(), nullable=False),
            StructField("patient_id", StringType(), nullable=True),
            StructField("patient_name", StringType(), nullable=True),
            StructField("study_date", StringType(), nullable=True),
            StructField("study_time", StringType(), nullable=True),
            StructField("accession_number", StringType(), nullable=True),
            StructField("study_description", StringType(), nullable=True),
            # CS VR — can contain multiple modalities, e.g. ["CT", "SR"]
            StructField("modalities_in_study", ArrayType(StringType()), nullable=True),
            StructField("number_of_study_related_series", LongType(), nullable=True),
            StructField("number_of_study_related_instances", LongType(), nullable=True),
            # Lineage: UC connection name that produced this record
            StructField("connection_name", StringType(), nullable=True),
        ]
    )

    # ---------------------------------------------------------------------------
    # Series-level schema
    # QIDO-RS /series
    # ---------------------------------------------------------------------------

    SERIES_SCHEMA = StructType(
        [
            StructField("series_instance_uid", StringType(), nullable=False),
            StructField("study_instance_uid", StringType(), nullable=True),
            StructField("study_date", StringType(), nullable=True),
            StructField("series_number", LongType(), nullable=True),
            StructField("series_description", StringType(), nullable=True),
            StructField("modality", StringType(), nullable=True),
            StructField("body_part_examined", StringType(), nullable=True),
            StructField("series_date", StringType(), nullable=True),
            # Lineage: UC connection name that produced this record
            StructField("connection_name", StringType(), nullable=True),
        ]
    )

    # ---------------------------------------------------------------------------
    # Instance (SOP) level schema
    # QIDO-RS /instances
    # ---------------------------------------------------------------------------

    INSTANCES_SCHEMA = StructType(
        [
            StructField("sop_instance_uid", StringType(), nullable=False),
            StructField("series_instance_uid", StringType(), nullable=True),
            StructField("study_instance_uid", StringType(), nullable=True),
            StructField("sop_class_uid", StringType(), nullable=True),
            StructField("instance_number", LongType(), nullable=True),
            StructField("study_date", StringType(), nullable=True),
            StructField("content_date", StringType(), nullable=True),
            StructField("content_time", StringType(), nullable=True),
            # Populated when fetch_dicom_files=true; path inside Unity Catalog Volume
            StructField("dicom_file_path", StringType(), nullable=True),
            # Full DICOM JSON for this instance; populated when fetch_metadata=true.
            StructField("metadata", VariantType(), nullable=True),
            # Lineage: UC connection name that produced this record
            StructField("connection_name", StringType(), nullable=True),
        ]
    )

    # ---------------------------------------------------------------------------
    # Diagnostics schema
    # WADO-RS / QIDO-RS capability probe results
    # ---------------------------------------------------------------------------

    DIAGNOSTICS_SCHEMA = StructType(
        [
            # Endpoint pattern, e.g. "/studies/{uid}/series/{uid}/instances/{uid}/frames/{n}"
            StructField("endpoint", StringType(), nullable=False),
            # Service category: QIDO-RS or WADO-RS
            StructField("category", StringType(), nullable=True),
            # Human-readable description of what the endpoint does
            StructField("description", StringType(), nullable=True),
            # "yes", "no", "unknown", or "error"
            StructField("supported", StringType(), nullable=False),
            # HTTP status code returned by the probe request (null on network error)
            StructField("status_code", LongType(), nullable=True),
            # Content-Type header from the response
            StructField("content_type", StringType(), nullable=True),
            # Round-trip latency in milliseconds
            StructField("latency_ms", LongType(), nullable=True),
            # Additional context: error message, Access Denied reason, etc.
            StructField("notes", StringType(), nullable=True),
            # ISO-8601 timestamp of this probe run (UTC)
            StructField("probe_timestamp", StringType(), nullable=False),
            # Lineage: UC connection name that produced this record
            StructField("connection_name", StringType(), nullable=True),
        ]
    )

    # ---------------------------------------------------------------------------
    # Lookup helpers
    # ---------------------------------------------------------------------------

    TABLE_SCHEMAS: dict[str, StructType] = {
        "studies": STUDIES_SCHEMA,
        "series": SERIES_SCHEMA,
        "instances": INSTANCES_SCHEMA,
        "diagnostics": DIAGNOSTICS_SCHEMA,
    }


    def get_schema(table_name: str) -> StructType:
        """Return the PySpark StructType for the given table name."""
        try:
            return TABLE_SCHEMAS[table_name]
        except KeyError:
            raise ValueError(f"Unknown table '{table_name}'. Valid tables: {list(TABLE_SCHEMAS)}")


    ########################################################
    # src/databricks/labs/community_connector/sources/dicomweb/dicomweb_utils_ext.py
    ########################################################

    def parse_value(value: Any, field_type: DataType) -> Any:
        """Extended parse_value with VariantType support.

        Shadows the parse_value from utils.py to add handling for VariantType.
        When field_type is VariantType and value is a JSON string, the string is
        converted to a VariantVal using VariantVal.parseJson(). If value is already
        a VariantVal it is returned unchanged. All other types fall through to the
        same logic as utils.parse_value.
        """
        if value is None:
            return None

        if isinstance(field_type, StructType):
            result = _parse_struct(value, field_type)
        elif isinstance(field_type, ArrayType):
            result = _parse_array(value, field_type)
        elif isinstance(field_type, MapType):
            result = _parse_map(value, field_type)
        elif isinstance(field_type, VariantType):
            result = VariantVal.parseJson(value) if isinstance(value, str) else value
        elif type(field_type) in _PRIMITIVE_PARSERS:
            result = _PRIMITIVE_PARSERS[type(field_type)](value)
        elif hasattr(field_type, "fromJson"):
            try:
                result = field_type.fromJson(value)
            except (ValueError, TypeError) as e:
                raise ValueError(
                    f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}"
                ) from e
        else:
            raise TypeError(f"Unsupported field type: {field_type}")
        return result


    ########################################################
    # src/databricks/labs/community_connector/sources/dicomweb/dicomweb.py
    ########################################################

    logger = logging.getLogger(__name__)

    # ---------------------------------------------------------------------------
    # Constants
    # ---------------------------------------------------------------------------

    SUPPORTED_TABLES = ("studies", "series", "instances", "diagnostics")
    DEFAULT_START_DATE = "19000101"  # Effectively "all history" on first run
    DEFAULT_PAGE_SIZE = 100
    DEFAULT_LOOKBACK_DAYS = 1
    DEFAULT_MAX_RECORDS_PER_BATCH = 500

    # WADO-RS retrieval mode
    WADO_MODE_AUTO = "auto"
    WADO_MODE_FULL = "full"
    WADO_MODE_FRAMES = "frames"


    # ---------------------------------------------------------------------------
    # Main connector
    # ---------------------------------------------------------------------------


    class DICOMwebLakeflowConnect(LakeflowConnect):
        """Lakeflow connector for DICOMweb VNA/PACS systems."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            base_url = options.get("base_url")
            if not base_url:
                raise ValueError("Connection option 'base_url' is required")

            self._client = DICOMwebClient(
                base_url=base_url,
                auth={
                    "username": options.get("username"),
                    "password": options.get("password"),
                    "token": options.get("token"),
                },
            )

            # Lineage identifier injected into every record.
            # Defaults to base_url so records are always traceable even when
            # the connection_name option is not explicitly set.
            self._connection_name: str = options.get("connection_name") or base_url

            # Cached WADO-RS mode detected at runtime (only used when wado_mode=auto)
            self._wado_mode_detected: str | None = None

            # Cap cursors at init time so a trigger never chases new data.
            # The next trigger creates a fresh instance and picks up from here.
            self._init_ts: str = date.today().strftime("%Y%m%d")

        # ------------------------------------------------------------------
        # Schema / metadata
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            return get_schema(table_name)  # raises ValueError for unknown tables

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(f"Unknown table '{table_name}'. Valid: {SUPPORTED_TABLES}")
            if table_name == "diagnostics":
                return {
                    "primary_keys": ["endpoint"],
                    "cursor_field": "probe_timestamp",
                    "ingestion_type": "cdc",
                }
            return {
                "primary_keys": [_primary_key(table_name)],
                "cursor_field": "study_date",
                "ingestion_type": "cdc",
            }

        # ------------------------------------------------------------------
        # Data reading
        # ------------------------------------------------------------------

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """
            Incrementally read records from the given table.

            Args:
                table_name:   One of "studies", "series", "instances", "diagnostics".
                start_offset: Previous offset dict, or {} for first run.
                table_options: Per-table options from the pipeline spec.

            Returns:
                (record_iterator, next_offset_dict)
            """
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(f"Unknown table '{table_name}'. Valid: {SUPPORTED_TABLES}")

            # Diagnostics table: runs a capability probe on every trigger, no cursor
            if table_name == "diagnostics":
                probe_iter = self._run_diagnostics_probe()
                next_offset = {"probe_timestamp": datetime.now(tz=timezone.utc).isoformat()}
                return probe_iter, next_offset

            start_offset = start_offset or {}
            date_cursor = start_offset.get("study_date", DEFAULT_START_DATE)
            page_offset = start_offset.get("page_offset", 0)

            # Short-circuit: cursor is at or past today — stream has caught up to init time.
            if start_offset and date_cursor >= self._init_ts:
                return iter([]), start_offset

            page_size = int(table_options.get("page_size", DEFAULT_PAGE_SIZE))
            max_records = int(
                table_options.get("max_records_per_batch", str(DEFAULT_MAX_RECORDS_PER_BATCH))
            )
            lookback_days = int(table_options.get("lookback_days", DEFAULT_LOOKBACK_DAYS))

            today_str = date.today().strftime("%Y%m%d")
            date_range = f"{_subtract_days(date_cursor, lookback_days)}-{today_str}"

            logger.info(
                "read_table table=%s date_range=%s page_offset=%d page_size=%d max_records=%d",
                table_name,
                date_range,
                page_offset,
                page_size,
                max_records,
            )

            if table_name == "studies":
                records, next_page_offset = self._collect_studies(
                    date_range, page_size, page_offset, max_records
                )
            elif table_name == "series":
                records, next_page_offset = self._collect_series(
                    date_range, page_size, page_offset, max_records
                )
            else:
                records, next_page_offset = self._collect_instances(
                    date_range, page_offset, table_options
                )

            if not records:
                end_offset = {"study_date": today_str, "page_offset": 0}
                if start_offset == end_offset:
                    return iter([]), start_offset
                return iter([]), end_offset

            end_offset = {"study_date": today_str, "page_offset": next_page_offset}
            if start_offset == end_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        # ------------------------------------------------------------------
        # Eager record collection (supports max_records_per_batch)
        # ------------------------------------------------------------------

        def _collect_studies(
            self, date_range: str, page_size: int, start_offset: int, max_records: int
        ) -> tuple[list[dict], int]:
            """Collect up to max_records studies via flat QIDO-RS pagination.

            Returns (records, next_page_offset) where next_page_offset is 0 when
            all pages are exhausted, or the study-level offset to resume from when
            the batch limit is hit mid-scan.
            """
            records: list[dict] = []
            offset = start_offset
            while len(records) < max_records:
                batch = self._client.query_studies(date_range, limit=page_size, offset=offset)
                if not batch:
                    return records, 0
                for raw in batch:
                    record = parse_study(raw)
                    record["connection_name"] = self._connection_name
                    records.append(record)
                if len(batch) < page_size:
                    return records, 0  # last partial page — all data consumed
                offset += page_size
            return records, offset  # hit batch limit; next call resumes from this offset

        def _collect_series(
            self, date_range: str, page_size: int, start_offset: int, max_records: int
        ) -> tuple[list[dict], int]:
            """Hierarchical series collection: enumerate studies, then fetch series per study.

            Returns (records, next_study_page_offset).
            """
            records: list[dict] = []
            study_offset = start_offset
            while len(records) < max_records:
                studies = self._client.query_studies(date_range, limit=page_size, offset=study_offset)
                if not studies:
                    return records, 0
                for study_raw in studies:
                    study = parse_study(study_raw)
                    study_uid = study.get("study_instance_uid")
                    if not study_uid:
                        continue
                    for series_raw in self._client.query_series_for_study(study_uid):
                        record = parse_series(series_raw)
                        # Propagate study_date / study_instance_uid from parent if missing
                        if not record.get("study_date"):
                            record["study_date"] = study.get("study_date")
                        if not record.get("study_instance_uid"):
                            record["study_instance_uid"] = study_uid
                        record["connection_name"] = self._connection_name
                        records.append(record)
                        if len(records) >= max_records:
                            break  # stop mid-series list
                    if len(records) >= max_records:
                        break  # stop mid-study page
                if len(records) >= max_records:
                    return records, study_offset  # hit limit; resume from same page next call
                if len(studies) < page_size:
                    return records, 0
                study_offset += page_size
            return records, study_offset

        def _collect_instances(
            self,
            date_range: str,
            start_offset: int,
            table_options: dict[str, str],
        ) -> tuple[list[dict], int]:
            """Hierarchical instances collection: enumerate studies → series → instances.

            Optionally fetches DICOM JSON metadata (fetch_metadata=true) and writes
            DICOM files to a UC Volume (fetch_dicom_files=true).

            Returns (records, next_study_page_offset).
            """
            page_size = int(table_options.get("page_size", DEFAULT_PAGE_SIZE))
            max_records = int(
                table_options.get("max_records_per_batch", str(DEFAULT_MAX_RECORDS_PER_BATCH))
            )
            records: list[dict] = []
            study_offset = start_offset
            while len(records) < max_records:
                studies = self._client.query_studies(date_range, limit=page_size, offset=study_offset)
                if not studies:
                    return records, 0
                for study_raw in studies:
                    study_records = self._collect_instances_for_study(study_raw, table_options)
                    records.extend(study_records)
                    if len(records) >= max_records:
                        return records[:max_records], study_offset
                if len(studies) < page_size:
                    return records, 0
                study_offset += page_size
            return records, study_offset

        def _collect_instances_for_study(
            self, study_raw: dict, table_options: dict[str, str]
        ) -> list[dict]:
            """Collect all instance records for a single study."""
            study = parse_study(study_raw)
            study_uid = study.get("study_instance_uid")
            if not study_uid:
                return []

            fetch_files = table_options.get("fetch_dicom_files", "false").lower() == "true"
            volume_path = table_options.get("dicom_volume_path", "")
            fetch_metadata = table_options.get("fetch_metadata", "false").lower() == "true"
            wado_mode = table_options.get("wado_mode", WADO_MODE_AUTO).lower()

            if fetch_files and not volume_path:
                raise ValueError("fetch_dicom_files=true requires dicom_volume_path to be set")

            records: list[dict] = []
            for series_raw in self._client.query_series_for_study(study_uid):
                series = parse_series(series_raw)
                series_uid = series.get("series_instance_uid")
                if not series_uid:
                    continue

                instances_raw = self._client.query_instances_for_series(study_uid, series_uid)
                sop_to_meta: dict[str, str] = {}
                if fetch_metadata:
                    sop_to_meta = self._build_metadata_map(study_uid, series_uid)

                for inst_raw in instances_raw:
                    record = parse_instance(inst_raw)
                    if not record.get("study_date"):
                        record["study_date"] = study.get("study_date")
                    if not record.get("study_instance_uid"):
                        record["study_instance_uid"] = study_uid
                    if not record.get("series_instance_uid"):
                        record["series_instance_uid"] = series_uid
                    if fetch_metadata:
                        sop_uid = record.get("sop_instance_uid")
                        record["metadata"] = sop_to_meta.get(sop_uid) if sop_uid else None
                    if fetch_files:
                        record = self._attach_dicom_file(record, volume_path, wado_mode)
                    record["connection_name"] = self._connection_name
                    records.append(record)
            return records

        # ------------------------------------------------------------------
        # WADO-RS helpers
        # ------------------------------------------------------------------

        def _attach_dicom_file(self, record: dict, volume_path: str, wado_mode: str) -> dict:
            """
            Retrieve the DICOM content via WADO-RS and write it to the Volume.

            Supports two retrieval modes:
            - full  (wado_mode=full):   GET .../instances/{uid}        → .dcm
            - frames (wado_mode=frames): GET .../instances/{uid}/frames/1 → .jpg

            When wado_mode=auto (default), the connector tries the full endpoint
            first.  If the server responds with 404/406/415 it switches to frame
            retrieval and caches the detected mode for the rest of the run.
            """
            study_uid = record.get("study_instance_uid")
            series_uid = record.get("series_instance_uid")
            sop_uid = record.get("sop_instance_uid")

            if not all([study_uid, series_uid, sop_uid]):
                logger.warning("Skipping WADO-RS: missing UIDs in record %s", record)
                return record

            try:
                effective_mode = self._resolve_wado_mode(wado_mode)
                if effective_mode == WADO_MODE_FRAMES:
                    file_bytes = self._client.retrieve_instance_frames(study_uid, series_uid, sop_uid)
                    ext = ".jpg"
                else:
                    # Try full DICOM retrieval; auto-detect fallback to frames on error
                    try:
                        file_bytes = self._client.retrieve_instance(study_uid, series_uid, sop_uid)
                        ext = ".dcm"
                        if wado_mode == WADO_MODE_AUTO and self._wado_mode_detected is None:
                            self._wado_mode_detected = WADO_MODE_FULL
                            logger.info("WADO-RS auto-detected: full DICOM retrieval")
                    except HTTPError as exc:
                        if wado_mode == WADO_MODE_AUTO and exc.code in (404, 406, 415):
                            logger.info(
                                "WADO-RS full instance returned HTTP %d "
                                "— auto-switching to frame retrieval",
                                exc.code,
                            )
                            self._wado_mode_detected = WADO_MODE_FRAMES
                            file_bytes = self._client.retrieve_instance_frames(
                                study_uid, series_uid, sop_uid
                            )
                            ext = ".jpg"
                        else:
                            raise
            except Exception as exc:
                logger.error("WADO-RS retrieval failed for %s: %s", sop_uid, exc)
                record["dicom_file_path"] = None
                return record

            dest_path_str = os.path.join(volume_path, study_uid, series_uid, f"{sop_uid}{ext}")
            os.makedirs(os.path.dirname(dest_path_str), exist_ok=True)
            with open(dest_path_str, "wb") as _f:
                _f.write(file_bytes)
            record["dicom_file_path"] = dest_path_str
            logger.debug("Wrote %d bytes → %s", len(file_bytes), dest_path_str)

            return record

        def _resolve_wado_mode(self, wado_mode: str) -> str:
            """Return the effective WADO mode, consulting the cached detection result."""
            if wado_mode == WADO_MODE_AUTO:
                return self._wado_mode_detected or WADO_MODE_FULL
            return wado_mode

        def _build_metadata_map(self, study_uid: str, series_uid: str) -> dict[str, str]:
            """
            Fetch WADO-RS series metadata and return a {sop_instance_uid: value} map.

            On DBR 15.x+ (METADATA_IS_VARIANT=True) values are VariantVal objects;
            on older runtimes they are JSON strings.  Returns an empty dict on any
            error so the instance record is still yielded without metadata.
            """
            try:
                meta_list = self._client.retrieve_series_metadata(study_uid, series_uid)
                sop_to_meta: dict[str, str] = {}
                for meta_obj in meta_list:
                    tag_obj = meta_obj.get("00080018")  # sop_instance_uid tag
                    if tag_obj and tag_obj.get("Value"):
                        sop_uid = str(tag_obj["Value"][0])
                        # VariantType: pass the Python dict — Spark's convert_variant
                        # handles dict → VARIANT binary encoding internally.
                        # StringType fallback: pass a JSON string for older runtimes.
                        sop_to_meta[sop_uid] = json.dumps(meta_obj)
                return sop_to_meta
            except Exception as exc:
                logger.warning("Failed to fetch series metadata %s/%s: %s", study_uid, series_uid, exc)
                return {}

        def _discover_sample_uids(self) -> tuple:
            """Discover sample study/series/instance UIDs for diagnostic probes."""
            study_uid = series_uid = sop_uid = None
            try:
                studies = self._client.query_studies("19000101-99991231", limit=1, offset=0)
                if studies:
                    study_uid = parse_study(studies[0]).get("study_instance_uid")
            except Exception as exc:
                logger.warning("Diagnostics: could not fetch a study UID: %s", exc)

            if study_uid:
                try:
                    series_list = self._client.query_series_for_study(study_uid)
                    if series_list:
                        series_uid = parse_series(series_list[0]).get("series_instance_uid")
                except Exception as exc:
                    logger.warning("Diagnostics: could not fetch a series UID: %s", exc)

            if study_uid and series_uid:
                try:
                    instances = self._client.query_instances_for_series(study_uid, series_uid)
                    if instances:
                        sop_uid = parse_instance(instances[0]).get("sop_instance_uid")
                except Exception as exc:
                    logger.warning("Diagnostics: could not fetch a SOP UID: %s", exc)

            return study_uid, series_uid, sop_uid

        def _run_diagnostics_probe(self) -> Iterator[dict]:
            """
            Probe all standard DICOMweb endpoints and yield one record per endpoint.

            Automatically discovers sample UIDs (study → series → instance) from the
            server so that hierarchical endpoints can be tested with real paths.
            Endpoints are never mutated — only GET requests are issued.
            """
            probe_timestamp = datetime.now(tz=timezone.utc).isoformat()
            study_uid, series_uid, sop_uid = self._discover_sample_uids()
            probes = _build_probe_definitions(study_uid, series_uid, sop_uid)

            for endpoint_pattern, path, category, description, accept in probes:
                if path is None:
                    yield {
                        "endpoint": endpoint_pattern,
                        "category": category,
                        "description": description,
                        "supported": "unknown",
                        "status_code": None,
                        "content_type": None,
                        "latency_ms": None,
                        "notes": "Could not probe — no sample UID available from the server",
                        "probe_timestamp": probe_timestamp,
                        "connection_name": self._connection_name,
                    }
                    continue

                result = self._client.probe_endpoint(path, accept=accept)
                supported, notes = _interpret_probe_status(result)
                yield {
                    "endpoint": endpoint_pattern,
                    "category": category,
                    "description": description,
                    "supported": supported,
                    "status_code": result["status_code"],
                    "content_type": result["content_type"],
                    "latency_ms": result["latency_ms"],
                    "notes": notes,
                    "probe_timestamp": probe_timestamp,
                    "connection_name": self._connection_name,
                }


    # ---------------------------------------------------------------------------
    # Helpers
    # ---------------------------------------------------------------------------


    def _build_probe_definitions(
        study_uid: str | None, series_uid: str | None, sop_uid: str | None
    ) -> list[tuple[str, str | None, str, str, str | None]]:
        """Build the list of DICOMweb probe endpoint definitions."""
        has_study = study_uid is not None
        has_series = has_study and series_uid is not None
        has_instance = has_series and sop_uid is not None
        return [
            (
                "/studies",
                "/studies?limit=1",
                "QIDO-RS",
                "Search studies (flat pagination)",
                None,
            ),
            (
                "/studies/{uid}/series",
                f"/studies/{study_uid}/series" if has_study else None,
                "QIDO-RS",
                "Search series for a study (hierarchical)",
                None,
            ),
            (
                "/studies/{uid}/series/{uid}/instances",
                f"/studies/{study_uid}/series/{series_uid}/instances" if has_series else None,
                "QIDO-RS",
                "Search instances for a series (hierarchical)",
                None,
            ),
            (
                "/studies/{uid}/series/{uid}/metadata",
                f"/studies/{study_uid}/series/{series_uid}/metadata" if has_series else None,
                "WADO-RS",
                "Series metadata — full DICOM JSON for all instances in a series",
                "application/dicom+json",
            ),
            (
                "/studies/{uid}/series/{uid}/instances/{uid}/metadata",
                (
                    f"/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/metadata"
                    if has_instance
                    else None
                ),
                "WADO-RS",
                "Instance metadata — full DICOM JSON for a single instance",
                "application/dicom+json",
            ),
            (
                "/studies/{uid}/series/{uid}/instances/{uid}",
                (
                    f"/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}"
                    if has_instance
                    else None
                ),
                "WADO-RS",
                "Retrieve full DICOM instance (.dcm, multipart/related)",
                'multipart/related; type="application/dicom"',
            ),
            (
                "/studies/{uid}/series/{uid}/instances/{uid}/frames/{n}",
                (
                    f"/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/frames/1"
                    if has_instance
                    else None
                ),
                "WADO-RS",
                "Retrieve pixel frame (image/jpeg or image/jls)",
                "image/jpeg, image/jls, application/octet-stream",
            ),
            (
                "/studies/{uid}/series/{uid}/instances/{uid}/rendered",
                (
                    f"/studies/{study_uid}/series/{series_uid}/instances/{sop_uid}/rendered"
                    if has_instance
                    else None
                ),
                "WADO-RS",
                "Retrieve rendered instance (viewport-ready PNG/JPEG)",
                "image/jpeg, image/png",
            ),
            (
                "/studies/{uid}/series/{uid}/rendered",
                f"/studies/{study_uid}/series/{series_uid}/rendered" if has_series else None,
                "WADO-RS",
                "Retrieve rendered series (all frames as viewport-ready images)",
                "image/jpeg, image/png",
            ),
            (
                "/studies/{uid}",
                f"/studies/{study_uid}" if has_study else None,
                "WADO-RS",
                "Retrieve entire study (all instances, multipart/related)",
                'multipart/related; type="application/dicom"',
            ),
        ]


    _STATUS_NOTES = {
        400: ("partial", "Bad Request (400) — endpoint exists but query parameters may be required"),
        403: ("no", "Access Denied (403) — endpoint blocked by server or CDN policy"),
        404: ("no", "Not Found (404) — endpoint not implemented on this server"),
        406: ("no", "Not Acceptable (406) — requested media type not supported"),
    }


    def _interpret_probe_status(result: dict) -> tuple[str, str]:
        """Interpret a probe result into (supported, notes)."""
        if result["error"]:
            return "error", result["error"]
        status = result["status_code"]
        if status in (200, 204, 206):
            return "yes", f"Content-Type: {result['content_type']}"
        return _STATUS_NOTES.get(status, ("no", f"HTTP {status}"))


    def _primary_key(table_name: str) -> str:
        pk_map = {
            "studies": "study_instance_uid",
            "series": "series_instance_uid",
            "instances": "sop_instance_uid",
            "diagnostics": "endpoint",
        }
        return pk_map[table_name]


    def _subtract_days(date_str: str, days: int) -> str:
        """Subtract `days` from a YYYYMMDD date string; clamp at DEFAULT_START_DATE."""
        if date_str == DEFAULT_START_DATE or days == 0:
            return date_str
        try:
            d = date(int(date_str[:4]), int(date_str[4:6]), int(date_str[6:8]))
            d = d - timedelta(days=days)
            return d.strftime("%Y%m%d")
        except (ValueError, IndexError):
            return date_str


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = DICOMwebLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
